services:
  db:
    # From https://hub.docker.com/_/postgres
    image: postgres:17
    restart: always
    shm_size: 128m
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: /home/angela/cosmin/Docker/postgres/data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
